# Generated by Django 4.0 on 2022-01-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_first_name_alter_user_user_type'),
        ('appointment', '0008_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='Nurse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Nurse_prescription', to='account.user'),
            preserve_default=False,
        ),
    ]
