# Generated by Django 4.0 on 2022-01-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_first_name_alter_user_user_type'),
        ('appointment', '0013_prescription_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nurse', to='account.user'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nurse_prescription', to='account.user'),
        ),
    ]
